# Site settings
title: Gesso
description: "A clean, simple Jekyll starter theme."
email: estrattonbailey@gmail.com
twitter_username: estrattonbailey
github_username:  estrattonbailey

keywords: "responsive, jekyll theme"

# Web Server Settings
url: "http://localhost:4000"
# url: "http://estrattonbailey.com"

# Hide these files from jekyll build process.
exclude: [README.md, scss/, raw/, style.css.map]

# Pagination settings.
paginate: 8
paginate_path: writings/page-:num

# Permalink setting for posts.
permalink: writings/:title

# Build settings
markdown: kramdown
